---
- hosts: "{{ target }}"
  roles:
    - { role: k8s/docker ,    tags: docker      }
    - { role: k8s/kubetools , tags: kube-tools  }
    - { role: k8s/hosts ,     tags: hosts       }
    - { role: k8s/user ,      tags: user        }